import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MdDarkMode } from "react-icons/md";
import Link from "next/link";
import { useState } from "react";
import React from "react";
import { Provider, useSelector } from 'react-redux';
import { store } from "./rtk/store";
import Navbar from "./Componants/page";
import StoreProvider from "./rtk/Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "where is my religion?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // let darktext = useSelector((state: any) => state.dark);
  // console.log(darktext)
  return (
    <html lang="en">
      <StoreProvider>
        <body className={inter.className} >
          <Navbar />
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
